### ISSUE TITLE
Runit issues with runit_service[zookeeper]

### ISSUE THREAD

**Issue by ctippur** [chef-cookbooks/runit#73] opened 2014-11-20 20:46 UTC
Hello,
I am having trouble getting runit service start zookeeper.

I get this error:
 Error executing action `enable` on resource 'runit_service[zookeeper]'
 Could not locate main runit sv_bin at "/sbin/sv". Did you remember to install runit before declaring a "runit_service" resource? 

cookbooks/zookeeper/recipes/service.rb has:
      49:   runit_service 'zookeeper' do
      50:     default_logger true
      51:     options({
     52:       exec: executable_path
      53:     })
      54:     action [:enable, :start]
     55:   end
      56: when 'exhibitor'

I see that runit is getting installed earlier. I also tried to including runit in the recipe cookbooks/zookeeper/recipes/service.rb

include_recipe "runit"

Appreciate any guidance.

- Shekar

**Comment by cwjohnston** [comment] 2015-12-16 22:10
Hello @ctippur! By now this issue seems to be quite old. Were you able to resolve the issue or can you reproduce it under the latest release?

**Comment by iennae** [comment] 2016-07-29 06:42
@ctippur as there hasn't been any movement on this issue, I'm going to go ahead and close it. If you still are having this issue, please reopen. Thanks!

**Closed by iennae** 2016-07-29 06:42 UTC
Labels: out of date?
